/** CSS custom properties supported by this component in the form designer. */
export const componentThemeTokens = [
  "--jb-switch-bar-border-color",
  "--jb-switch-bar-stroke-width",
  "--jb-switch-bg-color",
  "--jb-switch-bg-color-active",
  "--jb-switch-caption-color",
  "--jb-switch-caption-color-active",
  "--jb-switch-caption-font-size",
  "--jb-switch-caption-font-weight",
  "--jb-switch-caption-font-weight-active",
  "--jb-switch-cursor",
  "--jb-switch-focus-ring-color",
  "--jb-switch-gap",
  "--jb-switch-height",
  "--jb-switch-loading-animation-duration",
  "--jb-switch-opacity-disabled",
  "--jb-switch-ring-color",
  "--jb-switch-ring-color-active",
  "--jb-switch-transition",
  "--jb-switch-trigger-bg-color",
  "--jb-switch-trigger-bg-color-active",
  "--jb-switch-trigger-ring-stroke-width",
  "--jb-switch-width",
] as const;
