// Generated by src/features/form/component-data/sync-package-data.mjs. Edit the component folders.
export const COMPONENT_THEME_TOKEN_MIGRATIONS = {
  "jb-input": {
    "--jb-input-box-margin": "--jb-control-margin",
    "--jb-input-box-overflow": "--jb-control-overflow",
    "--jb-input-box-shadow": "--jb-control-shadow",
    "--jb-input-box-shadow-focus": "--jb-control-shadow-focus"
  },
  "jb-textarea": {
    "--jb-textarea-box-margin": "--jb-control-margin",
    "--jb-textarea-box-overflow": "--jb-control-overflow",
    "--jb-textarea-box-shadow": "--jb-control-shadow",
    "--jb-textarea-box-shadow-focus": "--jb-control-shadow-focus",
    "--jb-textarea-input-box-bg-color": "--jb-textarea-control-bg-color"
  }
} as const;
