// Generated by src/features/form/component-data/sync-package-data.mjs. Edit the component folders.
export const COMPONENT_PROPERTY_MIGRATIONS = {
  "jb-date-input": [
    {
      "from": "direction",
      "to": "dir"
    }
  ],
  "jb-file-input": [
    {
      "from": "acceptTypes",
      "to": "accept"
    }
  ],
  "jb-image-input": [
    {
      "from": "acceptTypes",
      "to": "accept"
    }
  ],
  "jb-select": [
    {
      "from": "hideClear",
      "to": "clearable",
      "invert": true
    }
  ],
  "jb-time-input": [
    {
      "from": "frontalZero",
      "to": "leadingZero"
    }
  ]
} as const;
