/** CSS custom properties supported by this component in the form designer. */
export const componentThemeTokens = [
  "--jb-checkbox-check-bg-color",
  "--jb-checkbox-check-bg-color-checked",
  "--jb-checkbox-check-bg-color-disabled",
  "--jb-checkbox-check-border-color",
  "--jb-checkbox-check-border-radius",
  "--jb-checkbox-check-border-radius-checked",
  "--jb-checkbox-check-mark-color",
  "--jb-checkbox-check-mark-color-checked",
  "--jb-checkbox-focus-ring-color",
  "--jb-checkbox-label-color",
  "--jb-checkbox-label-font-size",
  "--jb-checkbox-label-font-size-lg",
  "--jb-checkbox-label-font-size-sm",
  "--jb-checkbox-label-font-size-xl",
  "--jb-checkbox-label-font-size-xs",
  "--jb-checkbox-message-box-display",
  "--jb-checkbox-message-color",
  "--jb-checkbox-message-color-error",
  "--jb-checkbox-message-font-size",
  "--jb-checkbox-message-font-size-lg",
  "--jb-checkbox-message-font-size-sm",
  "--jb-checkbox-message-font-size-xl",
  "--jb-checkbox-message-font-size-xs",
  "--jb-checkbox-size",
  "--jb-checkbox-size-lg",
  "--jb-checkbox-size-sm",
  "--jb-checkbox-size-xl",
  "--jb-checkbox-size-xs",
] as const;
