/** CSS custom properties supported by this component in the form designer. */
export const componentThemeTokens = [
  "--jb-number-input-button-width",
  "--jb-number-input-button-width-lg",
  "--jb-number-input-button-width-md",
  "--jb-number-input-button-width-sm",
  "--jb-number-input-button-width-xl",
  "--jb-number-input-button-width-xs",
  "--jb-number-input-decrease-button-bg",
  "--jb-number-input-decrease-button-border",
  "--jb-number-input-decrease-button-border-radius",
  "--jb-number-input-decrease-button-color",
  "--jb-number-input-decrease-button-color-hover",
  "--jb-number-input-icon-size",
  "--jb-number-input-icon-size-lg",
  "--jb-number-input-icon-size-md",
  "--jb-number-input-icon-size-sm",
  "--jb-number-input-icon-size-xl",
  "--jb-number-input-icon-size-xs",
  "--jb-number-input-increase-button-bg",
  "--jb-number-input-increase-button-border",
  "--jb-number-input-increase-button-border-radius",
  "--jb-number-input-increase-button-color",
  "--jb-number-input-increase-button-color-hover",
  "--jb-number-input-input-direction",
] as const;
